# 博客基础配置
title: 我的GitHub博客  # 博客标题
email: 38413103@qq.com  # 你的邮箱
description: "这是我用GitHub Pages搭建的个人博客"  # 博客描述
baseurl: ""  # 固定为空（因为是根域名）
url: "https://mwp1981.github.io"  # 替换成你的博客地址
theme: minima  # GitHub Pages内置主题（可替换）
plugins:
  - jekyll-feed  # 可选：RSS订阅插件
